Function To Cast InferenceData Into `tidy_draws` Format
CDCgov/forecasttools-py pull request #36
Opened 2024-10-28 14:20 UTC by AFg6K7h4fhy2

2025-01-14 15:47 UTC, dylanhmorris commented on notebooks/idata_to_tidy_draws.py
> +                ".draw"
shouldn't this be `draw`?

2025-01-14 15:47 UTC, dylanhmorris commented on notebooks/idata_to_tidy_draws.py
> +        index=[".chain", ".iteration", ".draw"],
No dots I think
```suggestion
        index=["chain", "iteration", "draw"],
```

2025-01-21 21:34 UTC, damonbayer commented on notebooks/idata_to_tidy_draws.py
> +        index=[".chain", ".iteration", ".draw"],
Why not? This is the convention in tidybayes https://mjskay.github.io/tidybayes/articles/tidy-brms.html#gathering-variable-indices-into-a-separate-column-in-a-tidy-format-data-frame

2025-01-22 16:48 UTC, AFg6K7h4fhy2 reviewed
A quick self-review of this PR:

* `.csv` being ignored in `.gitignore` seems like a good practice.
* The `black` `pre-commit` hook will be fixed [^black].
* The R code in `./assets/external/` seems fine to me, but I can understand why others might not want these files in `forecasttools-py`. Middle ground might be a future document or README section that connects `forecasttools-py` implementations with those in `forecasttools` or `pyrenew`-based repositories.
* I believe citing software packages should be standard across CFA and CDCgov repositories. This explains the presence of `references.bib`. One place for the rendered references is the bottom of the README. 
* There are currently no tests, which ought to change in the near-term future.
* I have not uploaded the notebook in which I verify the function works on the `idata` Damon sent me.
* The `idata` Damon sent me _could_ exist packaged in `forecasttools-py` as an additional example `idata`.
* I need to verify whether `pandas` still needs to be in `dev` dependencies—this may be an artifact from my attempts solving the headache-inducing error from times past concerning the custom TimeStamp conversion. 

[^black]: The error received if not commented is: _Python 3.12.5 has a memory safety issue that can cause Black's AST safety checks to fail. Please upgrade to Python 3.12.6 or downgrade to Python 3.12.4_

2025-01-22 21:33 UTC, AFg6K7h4fhy2 commented on notebooks/pyrenew_dates_to_tidy.qmd
> +```
@dylanhmorris I would appreciate if you could look at the file `idata_to_tidy.py` in `./forecasttools` and aid me with solving this error.

2025-01-27 22:23 UTC, damonbayer commented on assets/external/idata_csv_to_tidy.R
No need to include if this is just repeating a function from forecasttools-R

2025-01-27 22:23 UTC, damonbayer commented on assets/external/inference_data_tidy.R
No need to include if this is just repeating a function from forecasttools-R

2025-01-27 22:28 UTC, damonbayer commented on assets/misc/references.bib
I don't think these references are useful, especially if they are not referred to in any documentation or readme. In the case that they were to be used in a readme or documentation, I don't see any advantage to storing a separate `.bib` file instead of just writing the reference in the text directly.

In addition, the `pyproject.toml` is a clear record of dependency between this library and jax/numpyro.

2025-01-27 22:32 UTC, dylanhmorris commented on assets/misc/references.bib
I was always skeptical here, but @AFg6K7h4fhy2 persuaded me. @AFg6K7h4fhy2 plans to write documentation/tutorials in quarto markdown. I think a `.bib` file is a reasonable (though not required) way to handle references for those docs.

2025-01-27 22:33 UTC, damonbayer commented on forecasttools/idata_to_tidy.py
> +def convert_idata_forecast_to_tidydraws(
1. This function does not only work on forecasts, so no need to mention that in the name.
2. ArviZ uses `inference_data` in function name for [functions that work with inference data](https://python.arviz.org/en/latest/api/generated/arviz.convert_to_inference_data.html). I suggest we follow this pattern.

Thus `convert_inference_data_to_tidydraws` would be my suggestion for the name.

2025-01-27 22:34 UTC, dylanhmorris commented on forecasttools/idata_to_tidy.py
> +def convert_idata_forecast_to_tidydraws(
^ Endorse

2025-01-27 22:35 UTC, AFg6K7h4fhy2 commented on assets/misc/references.bib
These are being moved to my sandbox.

2025-01-27 22:36 UTC, AFg6K7h4fhy2 commented on forecasttools/idata_to_tidy.py
> +def convert_idata_forecast_to_tidydraws(
I will follow this standard.

2025-01-27 23:09 UTC, damonbayer commented on assets/external/inference_data_1.nc
Generally skeptical of putting binary files in git repos. Would prefer a simple/fast way to recreate this or a similar file that can be used for the same purposes.

2025-01-27 23:17 UTC, AFg6K7h4fhy2 commented on assets/external/inference_data_1.nc
I will try to think of an alternative.

One possibility include demo-usage and then removal from the repository.

I assume you are talking about the `pyrenew` `idata`. 

The other `parquet` files and `.nc` files are package in `forecasttools` and cannot be removed without breaking the functionality of `forecasttools`.

2025-01-27 23:31 UTC, damonbayer commented on assets/external/inference_data_1.nc
Low priority, but we should think about replacing those files with scripts that generate those files (or minimal versions of those files, if they are complex to generate).

2025-01-27 23:32 UTC, damonbayer commented on assets/external/inference_data_1.nc
For example, in PyRenew-HEW we have https://github.com/CDCgov/pyrenew-hew/blob/main/pipelines/generate_test_data.R to generate "raw" data which is used in our tests, rather than storing the "raw" data itself.

2025-01-27 23:38 UTC, damonbayer commented on forecasttools/idata_to_tidy.py
> +    and read in R is tidy-usable.
No need to mention csv. It could be saved in any format that supports tabular data. Instead of tidy-usable, refer to the tidybayes API https://mjskay.github.io/tidybayes/articles/tidybayes.html

2025-01-27 23:38 UTC, AFg6K7h4fhy2 commented on assets/external/inference_data_1.nc
Seems reasonable for the `idata`, though the generation script would be long, and (not too meaningful a remark) re-introducing this code would be reversing an earlier-made decision to not have the generation code present. Thoughts for the packaged datasets used in a fair number of examples and also something that seems valuable to have a in a "forecast tools" package?

2025-01-27 23:39 UTC, damonbayer commented on forecasttools/idata_to_tidy.py
> +        idata object.
Why can't this be discerned from the idata object itself?

2025-01-27 23:40 UTC, AFg6K7h4fhy2 commented on forecasttools/idata_to_tidy.py
> +        idata object.
Since presumably we are not interested in every group that the `idata` contains. Further thoughts?

2025-01-27 23:40 UTC, damonbayer commented on forecasttools/idata_to_tidy.py
> +    idata_df = idata.to_dataframe()
recommend immediately converting to polars, so we aren't mixing polars and pandas throughout.

2025-01-27 23:41 UTC, damonbayer commented on forecasttools/idata_to_tidy.py
> +        value_columns = [col for col in group_pols_df.columns if col not in meta_columns]
Use polars selectors instead https://docs.pola.rs/api/python/stable/reference/selectors.html

2025-01-27 23:42 UTC, AFg6K7h4fhy2 commented on forecasttools/idata_to_tidy.py
> +    idata_df = idata.to_dataframe()
Will do, I agree with that assessment.

2025-01-27 23:44 UTC, dylanhmorris commented on forecasttools/idata_to_tidy.py
> +        idata object.
Default to all groups, allow the user to specify a desired subset?

2025-01-27 23:44 UTC, dylanhmorris commented on forecasttools/idata_to_tidy.py
> +        idata object.
Why wouldn't we want all groups by default?

2025-01-27 23:47 UTC, damonbayer commented on forecasttools/idata_to_tidy.py
> +                lambda x: re.sub(r"\[.*\]", "", x)).alias("variable")
Look into polars string capabilities instead? I think [`str.replace`](https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.replace.html) is the relevant bit.

2025-01-27 23:48 UTC, damonbayer commented on forecasttools/idata_to_tidy.py
> +        group_pols_df = group_pols_df.with_columns(
Use method chaining, rather than continually overwriting `group_pols_df`

2025-01-27 23:49 UTC, AFg6K7h4fhy2 commented on forecasttools/idata_to_tidy.py
> +        idata object.
> Why wouldn't we want all groups by default?

Do we want `log_likelihood` or `sample_stats` being converted / returned by default?

It seems that there would most often only be a subset of the `idata` being used.

If you want all groups, I would prefer:

> Default to all groups, allow the user to specify a desired subset?

2025-01-27 23:50 UTC, AFg6K7h4fhy2 commented on forecasttools/idata_to_tidy.py
> +    for group in groups:
Probably can, will attempt and remark if some question or issue.

2025-01-27 23:53 UTC, damonbayer commented on forecasttools/idata_to_tidy.py
> +    for group in groups:
Or maybe a dictionary comprehension?

2025-01-27 23:54 UTC, damonbayer commented on forecasttools/idata_to_tidy.py
> +            for col in group_df.columns
Just curious about what kinds of columns necessitate the conditional.

2025-01-27 23:55 UTC, AFg6K7h4fhy2 commented on forecasttools/idata_to_tidy.py
> +    for group in groups:
> Or maybe a dictionary comprehension?

This is what I was going to try.

2025-01-28 00:04 UTC, damonbayer commented on forecasttools/idata_to_tidy.py
> +        idata object.
Agree we should default to all groups. We should be grabbing the list of groups from the idata object anyway, so we can check that the group is valid before trying to pull it.

2025-01-28 00:06 UTC, damonbayer requested changes
Did an initial review for style / code smells. Have not tested for correctness yet.

2025-01-28 00:20 UTC, AFg6K7h4fhy2 commented
> Did an initial review for style / code smells. Have not tested for correctness yet.

Thank you for this [the thank you is usually implicit, but I feel that there were enough remarks in this first review to warrant writing this message].

2025-01-28 00:23 UTC, dylanhmorris commented on notebooks/pyrenew_dates_to_tidy.qmd
> +```
What does the actual tibble look like? Which draws are repeated? Is it the first one that errors?

2025-01-28 00:23 UTC, dylanhmorris commented on notebooks/pyrenew_dates_to_tidy.qmd
> +```
IOW best place to start is by inspecting the output.

2025-01-28 17:47 UTC, dylanhmorris commented on forecasttools/idata_to_tidy.py
> +        in the InferenceData.
This documentation should say something like "A list of groups to transform to tidy draws format" or similar.

2025-02-03 15:06 UTC, damonbayer commented on forecasttools/idata_to_tidy.py
> +    }
Line lengths are very long. Do you have a formatter in this project? 

In particular, I think readability would be enhanced by splitting something like
```python
group_cols = [col for col in idata_df.columns if col.startswith(f"('{group}',")]
renamed_cols = {col: col.split(", ")[1].strip("')") for col in group_cols}
```

2025-02-03 15:07 UTC, damonbayer commented on notebooks/pyrenew_dates_to_tidy.qmd
> +```
Is this bug still present?

2025-02-03 15:08 UTC, damonbayer reviewed
Reviewed again for code style. Can review for correctness if known bugs are squashed.

2025-02-03 15:10 UTC, damonbayer commented on forecasttools/idata_to_tidy.py
> +    }
This is also a place where you can use [polars selectors](https://docs.pola.rs/api/python/stable/reference/selectors.html), rather than grabbing `idata_df.columns` explicitly.

2025-02-03 15:32 UTC, damonbayer commented on forecasttools/idata_to_tidy.py
> +    }
If I'm not mistaken, some of the lines here appear to be more than 100 characters long.

2025-02-03 15:33 UTC, damonbayer commented on forecasttools/idata_to_tidy.py
> +    }
Using polars selectors seems like a better option than splitting the lines up.

2025-02-03 20:31 UTC, dylanhmorris commented on notebooks/pyrenew_dates_to_tidy.qmd
> +```
Also wondering this @AFg6K7h4fhy2

2025-02-03 20:32 UTC, dylanhmorris commented on forecasttools/idata_to_tidy.py
> +    }
Agree with @damonbayer on all counts.

2025-02-04 15:30 UTC, AFg6K7h4fhy2 commented on forecasttools/idata_to_tidy.py
> +    }
Some failed examples for posterior:

<details markdown=1>
```python
```{python}
import polars.selectors as cs
import polars as pl


df = pl.DataFrame(
    {
        "chain": [0, 1, 2, 3],
        "draw": [10, 20, 30, 40],
        "(a, var1)": [0.1, 0.2, 0.3, 0.4],
        "(a, var2)": [1.1, 1.2, 1.3, 1.4],
        "(b, var3)": [2.1, 2.2, 2.3, 2.4] 
    }
)

# want to use something like
# pl.col("*").filter(pl.col().name.str.starts_with(f"('{group}',"))

tidy_dfs = {
    group: df.select(
        #pl.col("chain", "draw"), 
        "chain",
        "draw",
        #pl.col(f"^\\({group},")
        #pl.col([col for col in df.columns if col.startswith(f"({group},")])
        #pl.col(f"^\({group},")
        #pl.col(f"^\\({group},")
        cs.starts_with(f"({group},")
        #pl.col("*").name.str.starts_with(f"('{group}',")
        #pl.col(pl.col().name.str.starts_with(f"('{group}',"))
    )
    for group in ["a", "b"]
}

print(tidy_dfs)
```
</details>

2025-02-04 20:44 UTC, AFg6K7h4fhy2 commented
Requested review from @dylanhmorris. Once a review is received, the author will request another review from Damon.

2025-02-04 21:20 UTC, dylanhmorris requested changes
Thanks @AFg6K7h4fhy2. Getting close but needs a few tweaks.

2025-02-04 21:20 UTC, dylanhmorris commented on .pre-commit-config.yaml
> +          "--ignore=W191",
[PEP8 strongly recommends spaces over tabs](https://peps.python.org/pep-0008/#tabs-or-spaces) for indenting Python code. You can configure your editor to insert four (or however many) spaces into Python code when you hit the tab key.

2025-02-04 21:20 UTC, dylanhmorris commented on forecasttools/__init__.py
Still not convinced we should have such a large top-level namespace, but that's not for this PR

2025-02-04 21:20 UTC, dylanhmorris commented on forecasttools/daily_to_epiweekly.py
> +import forecasttools
This risks creating a recursive import. If it doesn't currently that's only because `daily_to_epiweekly`'s functions are some of the only ones that aren't exposed by the top-level module. Should revert.

2025-02-04 21:20 UTC, dylanhmorris commented on forecasttools/idata_to_tidy.py
> +        from a numpyro forecast. Typically
Doesn't have to be numpyro or from a forecast. No need to name the groups.

2025-02-04 21:20 UTC, dylanhmorris commented on forecasttools/idata_to_tidy.py
> +                f"Invalid groups provided: {invalid_groups}."
```suggestion
                f"Requested groups {invalid_groups} not found in this InferenceData object."
```

2025-02-04 21:20 UTC, dylanhmorris commented on forecasttools/idata_to_tidy.py
> +                (pl.col(".chain") + 1).alias(".chain"),
Don't need the `.alias` for modify in place.
```suggestion
                pl.col(".iteration") + 1,
                pl.col(".chain") + 1
```

2025-02-04 21:20 UTC, dylanhmorris commented on forecasttools/idata_to_tidy.py
> +            )
If you do this earlier you don't need the -1.

2025-02-04 21:20 UTC, dylanhmorris commented on forecasttools/idata_to_tidy.py
> +            .melt(
`unpivot` is now preferred to `melt`
https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.unpivot.html#polars.DataFrame.unpivot

2025-02-04 21:20 UTC, dylanhmorris commented on forecasttools/idata_to_tidy.py
> +            )
Need to drop `"draws_per_chain"`, but also it's not a given that all chains will have the same number of draws. Instead, more robust do compute this as `.iteration + <n_draws_in_all_previous_chains`. Many ways to do that in polars.

2025-02-04 21:20 UTC, dylanhmorris commented on forecasttools/idata_w_dates_to_df.py
> +    if interval_dates.dtype != np.dtype("datetime64[ns]"):
neither of these is totally robust. See https://stackoverflow.com/questions/26921836/correct-way-to-test-for-numpy-dtype

Suggestion: use `issubdtype`. https://numpy.org/doc/stable/reference/generated/numpy.issubdtype.html

2025-02-04 21:20 UTC, dylanhmorris commented on forecasttools/idata_w_dates_to_df.py
> +    if interval_dates.dtype != np.dtype("datetime64[ns]"):
Out of scope for this PR, but please create an issue.

2025-02-04 21:20 UTC, dylanhmorris commented on tests/test_idata_to_tidy.py
> +    np.random.seed(42)
Running `np.random.seed` changes global state. Better practice to do something like this https://builtin.com/data-science/numpy-random-seed

2025-02-04 21:20 UTC, dylanhmorris commented on tests/test_idata_to_tidy.py
> +    )
Why not run the test on the provided `inference_data_1.nc`? Or are you planning to remove it?

2025-02-04 21:20 UTC, dylanhmorris commented on tests/test_idata_to_tidy.py
> +
Would be good to check that individual values are as expected, not just that the draws are unique and one for each row.

2025-02-06 14:32 UTC, AFg6K7h4fhy2 commented on tests/test_idata_to_tidy.py
> +    )
I am on the fence about removing it. Seems good to have a canonical `pyrenew-hew` `.nc` file on hand esp. given that `forecasttools-py` does / will even more so interface abundantly with `pyrenew` models. On the other hand, having adequate and general `idata` / `xarray` representations seems good for testing too. I do not know if the latter must exist at the cost of the former. I lean towards having both, with the `.nc` file perhaps being used in notebooks and the "fake" `idata`s being used for testing.

2025-02-06 14:37 UTC, AFg6K7h4fhy2 commented on forecasttools/__init__.py
Issue made here #62 .

2025-02-07 18:12 UTC, damonbayer commented on .pre-commit-config.yaml
Suggest doing this as a separate PR.

2025-03-12 14:58 UTC, AFg6K7h4fhy2 commented
A small note that the following historically worked but assumes all chains have the same number of iterations (in tidy-lingo):

<details markdown=1>

```python
tidy_dfs = {
        group: (
            idata_df.select("chain", "draw", cs.starts_with(f"('{group}',"))
            .rename(
                {
                    col: col.split(", ")[1].strip("')")
                    for col in idata_df.columns
                    if col.startswith(f"('{group}',")
                }
            )
            # draw in arviz is iteration in tidybayes
            .rename({"draw": ".iteration", "chain": ".chain"})
            .unpivot(
                index=[".chain", ".iteration"],
                variable_name="variable",
                value_name="value",
            )
            .with_columns(
                pl.col("variable").str.replace(r"\[.*\]", "").alias("variable")
            )
            .with_columns(pl.col(".iteration") + 1, pl.col(".chain") + 1)
            .with_columns(
                (pl.col(".iteration").n_unique()).alias("draws_per_chain"),
            )
            .with_columns(
                (
                    ((pl.col(".chain") - 1) * pl.col("draws_per_chain"))
                    + pl.col(".iteration")
                ).alias(".draw")
            )
            .pivot(
                values="value",
                index=[".chain", ".iteration", ".draw"],
                columns="variable",
                aggregate_function="first",
            )
            .sort([".chain", ".iteration", ".draw"])
        )
        for group in groups
    }
```

</details>

The method which does take into account the number of iterations per chain:

<details markdown=1>

```python
tidy_dfs = {
        group: (
            idata_df.select("chain", "draw", cs.starts_with(f"('{group}',"))
            .rename(
                {
                    col: col.split(", ")[1].strip("')")
                    for col in idata_df.columns
                    if col.startswith(f"('{group}',")
                }
            )
            # draw in arviz is iteration in tidybayes
            .rename({"draw": ".iteration", "chain": ".chain"})
            .unpivot(
                index=[".chain", ".iteration"],
                variable_name="variable",
                value_name="value",
            )
            .with_columns(
                pl.col("variable").str.replace(r"\[.*\]", "").alias("variable")
            )
            .with_columns(
                pl.col(".iteration") + 1, 
                pl.col(".chain") + 1)
            .pivot(
                values="value",
                index=[".chain", ".iteration"],
                columns="variable",
                aggregate_function="first",
            )
            .sort([".chain", ".iteration", ".draw"])
            .with_row_count(name=".draw", offset=1)
        )
        for group in groups
    }
```

</details>

2025-03-13 22:59 UTC, dylanhmorris requested changes
A few small but important things. Thanks, @AFg6K7h4fhy2!

2025-03-13 22:59 UTC, dylanhmorris commented on forecasttools/idata_to_tidy.py
> +    idata: az.InferenceData, groups: list[str]
```suggestion
    idata: az.InferenceData, groups: list[str] = None
```

2025-03-13 22:59 UTC, dylanhmorris commented on forecasttools/idata_to_tidy.py
> +                aggregate_function="first",
should be `None` [per the docs](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.pivot.html), no? (unless I'm misunderstanding what your goal is with this operation). You want one column for each unique value of `"variable"` for a given `".chain"` and `".iteration"`.

```suggestion
                aggregate_function=None,
```

https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.pivot.html

2025-03-13 22:59 UTC, dylanhmorris commented on tests/test_idata_to_tidy.py
> +def test_tidydraws_format(simple_inference_data):
This is nice, but I think it's important also to check the correct tidying of array-valued parameters. The example idata and associated test from forecasttools-R are nice and should be easily portable to Python

https://github.com/CDCgov/forecasttools/blob/main/data-raw/ex_inferencedata_dataframe.R
https://github.com/CDCgov/forecasttools/blob/main/tests/testthat/test_inferencedata_dataframe_to_tidydraws.R

2025-03-14 00:14 UTC, AFg6K7h4fhy2 commented on forecasttools/idata_to_tidy.py
> +                aggregate_function="first",
For the actual `pyrenew` inference data object, but not for the other examples I have made, using `None` and not `first` produces this error:

> FAILED tests/test_idata_to_tidy.py::test_posterior_predictive_group - polars.exceptions.ComputeError: found multiple elements in the same group, please specify an aggregation function

2025-03-14 00:17 UTC, AFg6K7h4fhy2 commented on tests/test_idata_to_tidy.py
> +def test_tidydraws_format(simple_inference_data):
I will save this task for 2025-03-14.

2025-03-14 00:35 UTC, dylanhmorris commented on forecasttools/idata_to_tidy.py
> +                aggregate_function="first",
That suggests something is not correct upstream. Perhaps the variable name regex?

2025-03-18 14:19 UTC, AFg6K7h4fhy2 commented on forecasttools/idata_to_tidy.py
> +                aggregate_function="first",
I believe the source of this issue is the line in `col: col.split(", ")[1].strip("')")`

```
.rename(
    {
        col: col.split(", ")[1].strip("')")
        for col in idata_df.columns
        if col.startswith(f"('{group}',")
    }
)
```

2025-03-18 16:16 UTC, AFg6K7h4fhy2 commented on forecasttools/idata_to_tidy.py
> +                aggregate_function="first",
I changed

`col: col.split(", ")[1].strip("')")`

to

`col: re.search(r",\s*'?(.+?)'?\)", col).group(1)`

which I got incorrect a handful of times but which I believe works now. 

The target of this regex looks like, e.g.,  `"('posterior', 'alpha')"`. 

In the expression, the `,` matches comma; in `\s*`, the `\s` is spaces and `*` for zero or more spaces; in `'?`, the `'` means single quote and `?` means optional (0 or 1 times); in `(.+?)`, the `(` and `)` capture whatever is in the parenthesis with `.` means non-newline character, `+` means one or more characters, and `?` (which I am not sure is necessary to include here) tries to get this capture in as small a job as possible (this capture will get `alpha` in the example target); the `'?` is the same as before; the `\)` is the single closing parenthesis after the group (the `\` is needed for escaping parenthesis; and `.group(1)` in `re` gets the first item captured by `(.+?)`.

2025-03-18 16:43 UTC, dylanhmorris commented on forecasttools/idata_to_tidy.py
> +                    col: re.search(r",\s*'?(.+?)'?\)", col).group(1)
Feels like this would be better handled by providing a lambda rename mapping to `.rename()` rather than via dictionary comprehension. See https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.rename.html

2025-03-18 16:55 UTC, AFg6K7h4fhy2 commented on forecasttools/idata_to_tidy.py
> +                    col: re.search(r",\s*'?(.+?)'?\)", col).group(1)
Hadn't thought of this. In the back of mind there are reservations I've seen from others that I haven't verified regarding about lambda mappings but they're not sufficient to not act here. Polars `rename` seems apt. Thank you for the quick comment.

2025-03-18 17:03 UTC, AFg6K7h4fhy2 commented on forecasttools/idata_to_tidy.py
> +                    col: re.search(r",\s*'?(.+?)'?\)", col).group(1)
I changed the code to:

```
.rename(
    lambda col: re.search(r",\s*'?(.+?)'?\)", col).group(1)
    if col.startswith(f"('{group}',")
    else col
)
```

got 

```
forecasttools/idata_to_tidy.py:66:40: B023 Function definition does not bind loop variable `group`
```

then changed to:


```
.rename(
    lambda col, group=group: re.search(
        r",\s*'?(.+?)'?\)", col
    ).group(1)
    if col.startswith(f"('{group}',")
    else col
)
```

which works w/ tests & linting. 

Commenting above for my future self.

2025-03-18 17:17 UTC, dylanhmorris commented on forecasttools/idata_to_tidy.py
> +                    col: re.search(r",\s*'?(.+?)'?\)", col).group(1)
1. Readability concern: at least two different senses of "group" present here.

2. I'd make it a one argument `lambda` and exclude it from linting. Making "group" an argument that defaults to the value of `group` satisfies the linter but hurts readability imo 
```
forecasttools/idata_to_tidy.py:66:40: B023 Function definition does not bind loop variable `group`
```

2025-03-18 18:01 UTC, damonbayer commented on forecasttools/idata_to_tidy.py
> +                aggregate_function="first",
Can you write a test to demonstrate the case where the previous version was failing and the new version succeeds? They both work correctly on the example provided in your comment: `"('posterior', 'alpha')"`.

2025-03-19 01:37 UTC, AFg6K7h4fhy2 commented on forecasttools/idata_to_tidy.py
> +                aggregate_function="first",
The split approach did not work on the InferenceData object from `pyrenew-hew` in tests when the aggregate function was not set to `first`. Yes, both the split and `re` approaches work on "('posterior', 'alpha')".

2025-03-19 01:38 UTC, AFg6K7h4fhy2 commented on forecasttools/idata_to_tidy.py
> +                aggregate_function="first",
Thank you for comment + I will write test.

2025-03-19 01:39 UTC, AFg6K7h4fhy2 commented on forecasttools/idata_to_tidy.py
> +                    col: re.search(r",\s*'?(.+?)'?\)", col).group(1)
Re: <https://github.com/CDCgov/forecasttools-py/pull/36#discussion_r2001563816>

Will do. I agree, `group=group` seems extraneous but my usual response is to defer to the linter.

2025-03-21 17:39 UTC, AFg6K7h4fhy2 commented on forecasttools/idata_to_tidy.py
> +                aggregate_function="first",
> The split approach did not work on the InferenceData object from pyrenew-hew in tests when the aggregate function was set to None but did work when the aggregate function was set to first. Yes, both the split and re approaches work on "('posterior', 'alpha')".

I should probably investigate why, exactly, aggregate=None w/ split doesn't work for the Pyrenew inference data.

2025-08-21 21:29 UTC, damonbayer commented
Closing in light of https://github.com/CDCgov/polarbayes

2025-08-21 21:29 UTC, closed without merging